server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: store
          uri: http://localhost:8082
          predicates:
            - Path=/owners/**, 
        - id: Rider
          uri: http://localhost:8083
          predicates:
            - Path=/riders/**, 
        - id: DashBoard
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: front
          uri: http://front:8080
          predicates:
            - Path=/orders/**, 
        - id: store
          uri: http://store:8080
          predicates:
            - Path=/owners/**, 
        - id: Rider
          uri: http://rider:8080
          predicates:
            - Path=/riders/**, 
        - id: DashBoard
          uri: http://dashBoard:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
